### ISSUE TITLE
Invalid scss file causes scss-lint to hang

### ISSUE THREAD

**Issue by mhujer** [causes/scss-lint#329]
If I have a file `test.scss` with this content (see the missing semicolon after the `!important`):
```
.foo {
    margin-top: 0 !important
}
```

and run `scss-lint test.scss`, it hangs (it works fine when the semicolon is there or the `!important` is not there)

**Comment by sds** [comment]
Thanks for the report, @mhujer. 

Fixed in d8be7c5125e68b963111a538c162b425cddf3e2e.

**Comment by mhujer** [comment]
:+1:
