### ISSUE TITLE
“can't dup NilClass”

### ISSUE THREAD

**Issue by yellowled** [causes/scss-lint#330]
System is OS X 10.10.1, ruby is 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin14], scss-lint is 0.31.0.

Using scss-lint manually or with grunt-scss-lint, I get the following on any `.scss` file I have tested:

```
$ scss-lint master.scss
can't dup NilClass
/Library/Ruby/Gems/2.0.0/gems/scss-lint-0.31.0/lib/scss_lint/config.rb:159:in `dup'
/Library/Ruby/Gems/2.0.0/gems/scss-lint-0.31.0/lib/scss_lint/config.rb:159:in `ensure_exclude_paths_are_absolute'
/Library/Ruby/Gems/2.0.0/gems/scss-lint-0.31.0/lib/scss_lint/config.rb:151:in `block in ensure_linter_exclude_paths_are_absolute'
/Library/Ruby/Gems/2.0.0/gems/scss-lint-0.31.0/lib/scss_lint/config.rb:149:in `each'
/Library/Ruby/Gems/2.0.0/gems/scss-lint-0.31.0/lib/scss_lint/config.rb:149:in `ensure_linter_exclude_paths_are_absolute'
/Library/Ruby/Gems/2.0.0/gems/scss-lint-0.31.0/lib/scss_lint/config.rb:80:in `load_options_hash_from_file'
/Library/Ruby/Gems/2.0.0/gems/scss-lint-0.31.0/lib/scss_lint/config.rb:21:in `load'
/Library/Ruby/Gems/2.0.0/gems/scss-lint-0.31.0/lib/scss_lint/config.rb:37:in `for_file'
/Library/Ruby/Gems/2.0.0/gems/scss-lint-0.31.0/lib/scss_lint/cli.rb:132:in `block in files_to_lint'
/Library/Ruby/Gems/2.0.0/gems/scss-lint-0.31.0/lib/scss_lint/cli.rb:130:in `reject'
/Library/Ruby/Gems/2.0.0/gems/scss-lint-0.31.0/lib/scss_lint/cli.rb:130:in `files_to_lint'
/Library/Ruby/Gems/2.0.0/gems/scss-lint-0.31.0/lib/scss_lint/cli.rb:51:in `scan_for_lints'
/Library/Ruby/Gems/2.0.0/gems/scss-lint-0.31.0/lib/scss_lint/cli.rb:45:in `act_on_options'
/Library/Ruby/Gems/2.0.0/gems/scss-lint-0.31.0/lib/scss_lint/cli.rb:25:in `run'
/Library/Ruby/Gems/2.0.0/gems/scss-lint-0.31.0/bin/scss-lint:6:in `<top (required)>'
/usr/bin/scss-lint:23:in `load'
/usr/bin/scss-lint:23:in `<main>'
```
Happy to give more information or do more testing if needed, but I'm afraid I'm going to need specific instructions. I'm not a ruby guy. :)

**Comment by sds** [comment]
Hey @yellowled, thanks for the report.

Can you include your `.scss-lint.yml` file? This appears to be something to do with the configuration you're using, as it's not clear how you got into this state (and I can't reproduce locally).

**Comment by yellowled** [comment]
Right, sorry. [.scss-lint.yml](https://github.com/yellowled/yl-bp/blob/master/.scss-lint.yml)

**Comment by sds** [comment]
Ah, your `BangFormat` options are not indented correctly. They should be written like this:

```yaml
  BangFormat:
    enabled: true
    space_before_bang: true
    space_after_bang: false
```

...not this:

```yaml
  BangFormat:
  enabled: true
  space_before_bang: true
  space_after_bang: false
```

There might be something `scss-lint` can do to detect this and present a friendlier warning, so I'll leave this issue open for now. Thanks!

**Comment by yellowled** [comment]
Thanks, that fixes the error message for me. Guess I got screwed by automagic ruby indentation on that one.

**Comment by sds** [comment]
There isn't really a terribly elegant way of dealing with this that doesn't involve overly complicating the `Config` class, which is complex enough as it is.

Thanks for the report. Until we see more people tripped up by this, we're going to leave this as-is for now.

**Comment by grrowl** [comment]
+1 tripped me up today, and indeed it was an yaml parse error (a stray single space, incorrectly indented comment, a `UnnecessaryParentReference:` without any values within).
