### ISSUE TITLE
Allow BorderZero to unify to border: none

### ISSUE THREAD

**Issue by Anahkiasen** [causes/scss-lint#341]
It would be nice if instead of being a boolean, the BorderZero would be a string to allow you to lint that _only_ `border: none` is used instead, as that is what I've most often seen used in the wild. 

```yaml
BorderZero:
  convention: 'none'
```

Like that or something

**Comment by lencioni** [comment]
Thanks for the suggestion! This makes sense to me. We'd gladly accept a pull request that adds this feature.

**Comment by sds** [comment]
Added in f878fd5b4475c83d08dad66458bb8c507d84e148.
