### ISSUE TITLE
Auto-correcting

### ISSUE THREAD

**Issue by Dorian** [causes/scss-lint#343]
Most things can be autocorrected (eg: colors, paddings, margins, order of rules, etc...)

Similar to [rubocop](https://github.com/bbatsov/rubocop)'s `--auto-correct`

> -a/--auto-correct	Auto-correct certain offenses. Note: Experimental - use with caution.

**Comment by Anahkiasen** [comment]
Would really love this, in particular for properties order which is really painful and long to correct on big codebases

**Comment by Dorian** [comment]
Yep, I think with CSS 95% of the "warnings" I got are auto-correctable (eg: the "line too longs", "too many nested rules", ... are impossible to auto-correct automaticaly

**Comment by sds** [comment]
This is far from trivial, and so I don't think it is a worthwhile pursuit in `scss-lint`.

The `rubocop` project enjoyed this capability thanks to the underlying `parser` gem that they use. There is no matching capability available with the `sass` parser, and without that this sort of feature becomes an entire project unto itself.

Thus, as mentioned in #282, unless some very enthusiastic volunteer implements a custom Sass parser with tree mutation capability, you will not see this in `scss-lint`.

Hope that makes sense.

**Comment by Dorian** [comment]
Hmm, yes right I think this should be another project, I might a simple regexp based + basic rule sorting one.

**Comment by Dorian** [comment]
Actually I started a repo with some basic regexp based scripts: https://github.com/Dorian/scss-lint-auto-correct
