### ISSUE TITLE
Issue on version 0.33.0

### ISSUE THREAD

**Issue by lcalvy** [causes/scss-lint#352]
Error after upgrading from 0.29.0 to 0.33.0

scss-lint -c grunt/rc/scss-lint.yml core/public/sass/core/__core-expose.scss core/public/sass/core/__core.scss core/public/sass/core/atom/_Duration.scss core/public/sass/core/atom/__atoms.scss core/public/sass/core/atom/_avatar.scss core/public/sass/core/atom/_badge.scss core/public/sass/core/atom/_block.scss core/public/sass/core/atom/_chipTitle.scss core/public/sass/core/atom/_counter.scss core/public/sass/core/atom/_filters.scss core/public/sass/core/atom/_iconButton.scss core/public/sass/core/atom/_level.scss core/public/sass/core/atom/_logo.scss core/public/sass/core/atom/_navLink.scss core/public/sass/core/atom/_selectLanguage.scss core/public/sass/core/atom/buttons/_CoachButton.scss core/public/sass/core/atom/buttons/_abstracts.scss core/public/sass/core/atom/buttons/_mainNavButton.scss core/public/sass/core/atom/buttons/_moduleButton.scss core/public/sass/core/atom/buttons/_userNavButton.scss core/public/sass/core/atom/text/_abstracts.scss core/public/sass/core/atom/text/_defaultText.scss core/public/sass/core/atom/text/_highlightedText.scss core/public/sass/core/atom/titles/_abstracts.scss core/public/sass/core/atom/titles/_defaultTitle.scss core/public/sass/core/atom/titles/_mainTitles.scss core/public/sass/core/atom/titles/_popinTitles.scss core/public/sass/core/atom/titles/_subTitles.scss core/public/sass/core/molecule/__molecules.scss core/public/sass/core/molecule/_blockCms.scss core/public/sass/core/molecule/_blockPush.scss core/public/sass/core/molecule/_card.scss core/public/sass/core/molecule/_chapterMenu.scss core/public/sass/core/molecule/_checkbox.scss core/public/sass/core/molecule/_dashboardPushes.scss core/public/sass/core/molecule/_disclaimer.scss core/public/sass/core/molecule/_entireBadge.scss core/public/sass/core/molecule/_evergreenBrowserList.scss core/public/sass/core/molecule/_inlineListModule.scss core/public/sass/core/molecule/_notifications.scss core/public/sass/core/molecule/_splashscreen.scss core/public/sass/core/molecule/_userCartouche.scss core/public/sass/core/molecule/_yourScore.scss core/public/sass/core/molecule/inlineList/_inlineList.scss core/public/sass/core/organism/__organisms.scss core/public/sass/core/organism/_battleMode.scss core/public/sass/core/organism/_footer.scss core/public/sass/core/organism/_header.scss core/public/sass/core/organism/_learningTree.scss core/public/sass/core/page/__pages.scss core/public/sass/core/page/_dashboard.scss core/public/sass/core/quark/__quarks.scss core/public/sass/core/quark/elements/__elements.scss core/public/sass/core/quark/elements/_all.scss core/public/sass/core/quark/elements/_body.scss core/public/sass/core/quark/elements/_html.scss core/public/sass/core/quark/elements/_others.scss core/public/sass/core/template/__templates.scss core/public/sass/core/template/_dashboard.scss core/public/sass/core/template/_master.scss core/public/sass/core/utilities/__utilities.scss core/public/sass/core/utilities/functions/__functions.scss core/public/sass/core/utilities/functions/_pxToEm.scss core/public/sass/core/utilities/mixins/__mixins.scss core/public/sass/core/utilities/variables/__variables.scss core/public/sass/core/utilities/variables/_mq.scss
no implicit conversion of String into Hash
/usr/local/lib/ruby/gems/2.1.0/gems/scss-lint-0.33.0/lib/scss_lint/config.rb:194:in `merge'
/usr/local/lib/ruby/gems/2.1.0/gems/scss-lint-0.33.0/lib/scss_lint/config.rb:194:in `smart_merge'
/usr/local/lib/ruby/gems/2.1.0/gems/scss-lint-0.33.0/lib/scss_lint/config.rb:199:in `block in smart_merge'
/usr/local/lib/ruby/gems/2.1.0/gems/scss-lint-0.33.0/lib/scss_lint/config.rb:194:in `merge'
/usr/local/lib/ruby/gems/2.1.0/gems/scss-lint-0.33.0/lib/scss_lint/config.rb:194:in `smart_merge'
/usr/local/lib/ruby/gems/2.1.0/gems/scss-lint-0.33.0/lib/scss_lint/config.rb:199:in `block in smart_merge'
/usr/local/lib/ruby/gems/2.1.0/gems/scss-lint-0.33.0/lib/scss_lint/config.rb:194:in `merge'
/usr/local/lib/ruby/gems/2.1.0/gems/scss-lint-0.33.0/lib/scss_lint/config.rb:194:in `smart_merge'
/usr/local/lib/ruby/gems/2.1.0/gems/scss-lint-0.33.0/lib/scss_lint/config.rb:24:in `load'
/usr/local/lib/ruby/gems/2.1.0/gems/scss-lint-0.33.0/lib/scss_lint/cli.rb:90:in `setup_configuration'
/usr/local/lib/ruby/gems/2.1.0/gems/scss-lint-0.33.0/lib/scss_lint/cli.rb:45:in `act_on_options'
/usr/local/lib/ruby/gems/2.1.0/gems/scss-lint-0.33.0/lib/scss_lint/cli.rb:25:in `run'
/usr/local/lib/ruby/gems/2.1.0/gems/scss-lint-0.33.0/bin/scss-lint:6:in `<top (required)>'
/usr/local/bin/scss-lint:23:in `load'
/usr/local/bin/scss-lint:23:in `<main>'
Report this bug at https://github.com/causes/scss-lint/issues

**Comment by sds** [comment]
Hey @lcalvy, thanks for the report.

It would be very helpful if you could post your `grunt/rc/scss-lint.yml` configuration file, as without it I'm afraid it's not obvious what could be causing the problem.

Thanks!

**Comment by sds** [comment]
Closing due to lack of response.

**Comment by lcalvy** [comment]
hi, sorry for delay

# Default application configuration that all configurations inherit from.
linters:
  BorderZero:
    enabled: true

  CapitalizationInSelector:
    enabled: false

  ColorKeyword:
    enabled: true

  Comment:
    enabled: false

  DebugStatement:
    enabled: true

  DeclarationOrder:
    enabled: true

  DuplicateProperty:
    enabled: true

  EmptyLineBetweenBlocks:
    enabled: true
    ignore_single_line_blocks: true

  ElsePlacement:
    style: new_line

  EmptyRule:
    enabled: true

  FinalNewline:
    enabled: true
    present: true

  HexLength:
    enabled: true
    style: short # or 'long'

  HexNotation:
    enabled: true
    style: lowercase # or 'uppercase'

  HexValidation:
    enabled: true

  IdWithExtraneousSelector:
    enabled: true

  Indentation:
    enabled: true
    width: 4

  LeadingZero:
    enabled: true
    style: exclude_zero # or 'include_zero'

  MergeableSelector:
    enabled: true
    force_nesting: true

  NameFormat:
    enabled: false
    convention: hyphenated_lowercase # or 'BEM', or a regex pattern

  PlaceholderInExtend:
    enabled: true

  PropertySortOrder:
    enabled: true
    order: concentric

  PropertySpelling:
    enabled: true
    extra_properties: []

  SelectorDepth:
    enabled: true
    max_depth: 3

  Shorthand:
    enabled: true

  SingleLinePerSelector:
    enabled: true

  SpaceAfterComma:
    enabled: true

  SpaceAfterPropertyColon:
    enabled: true

  SpaceAfterPropertyName:
    enabled: true

  SpaceBeforeBrace:
    enabled: true
    allow_single_line_padding: false

  SpaceBetweenParens:
    enabled: true
    spaces: 0

  StringQuotes:
    enabled: true
    style: single_quotes # or double_quotes

  TrailingSemicolonAfterPropertyValue:
    enabled: true

  UnnecessaryMantissa:
    enabled: true

  UrlFormat:
    enabled: true

  UrlQuotes:
    enabled: true

  ZeroUnit:
    enabled: true

  Compass::*:
    enabled: false

  SelectorFormat:
    enabled:false

**Comment by sds** [comment]
Hey @lcalvy,

The problem is your last line. You need a space separating `enabled:` from `false`, otherwise it does not get parsed as a hash key in YAML.

Hope that helps!

**Comment by lcalvy** [comment]
you right. it's ok

thank you
