### ISSUE TITLE
Allow linting any file

### ISSUE THREAD

**Issue by joshuaspence** [causes/scss-lint#363]
It would be nice if `scss-lint` allowed linting any file. Currently, it is only possibly to lint `*.scss` files.

```
> scss-lint file.txt
No SCSS files specified
```

**Comment by bartveneman** [comment]
Perhaps a good use case to name here: mustache templates used for generating sprite scss files, like in [gulp-svg-sprite](https://github.com/jkphl/gulp-svg-sprite). Now I declare the generation of the scss file a dependency for the scss-lint task, but ideally it would be better to test the mustache.scss file.

**Comment by lencioni** [comment]
Are the files that you want to lint actually parseable by Sass? If they are not, allowing non-`.scss` file extensions will not benefit you very much since scss-lint relies on the Sass parser to do its work.

**Comment by sds** [comment]
I've added support for this in 5343c703. I was actually under the impression we already supported this, but I guess we never go around to it.

I agree that this should be used with care as it's quite likely that a non-standard extension usually means it won't parse. However, if a user is being explicit about the file they wish to lint I don't see any reason to stop them from using an alternate extension.
