### ISSUE TITLE
allow_non_nested_indentation not working correctly

### ISSUE THREAD

**Issue by nenadjelovac** [causes/scss-lint#374]
It works only for non nested class but everything else within it is being reported as error for not being indented correctly.

Please see [screenshot here](http://gyazo.com/3ef8d8852c005b04ce364434fd0dfaa4) (Sublime3, OS X).

**Comment by meowsus** [comment]
I'm seeing this too.

**Comment by himedlooff** [comment]
I have the same issue as @nenadjelovac.

**Comment by sds** [comment]
Fixed by 53494a8.

**Comment by meowsus** [comment]
Excellent! Do you know when this will be released?

**Comment by sds** [comment]
Version [0.35.0](https://github.com/causes/scss-lint/releases/tag/v0.35.0) includes this fix.
