### ISSUE TITLE
Possibly redundant rule?

### ISSUE THREAD

**Issue by gunnx** [causes/scss-lint#381]
The linter ColorVariable and VariableForProperty seem to do the same job, is there a use case to keep ColorVariable?

**Comment by sds** [comment]
They seem similar, but actually serve different purposes.

`VariableForProperty` allows you to specify a customizable list of properties that you always want to be assigned a variable as a value. The common use case is for the `color` property.

The `ColorVariable` reports the use of _any_ color literal outside of a variable declaration. It has nothing to do with property values&mdash;it only enforces that color literals are used in one place.

Thus the two use cases are different. Hope that explains things.
