### ISSUE TITLE
file not found dumps stack trace

### ISSUE THREAD

**Issue by masi** [causes/scss-lint#390]
scscc-lint does-no-exist.scss doesn't display a nice error message. Instead I get "can't modify frozen String" along with a stack trace and a note to report the issue at GitHub. Hereby I comply :)

Masi

**Comment by sds** [comment]
Hey @masi,

Next time, it would be helpful if you posted the stack trace with the bug report. It makes the investigation much easier.

Fortunately, I am able to reproduce this locally. Thanks for the report.

**Comment by sds** [comment]
Fixed in b0de02f59ec5c376e2e5d73e673ffea96e9dd826.
