### ISSUE TITLE
NameFormat applies to CSS functions?

### ISSUE THREAD

**Issue by masi** [causes/scss-lint#391]
I thought that NameFormat would apply to SASS functions, but not to CSS functions. I have allowed vendor prefixes but enforce camel case for variables. At least I thought so.

Now I get an error for this property definition:

background-image: -moz-linear-gradient(bottom, $bottomColor $bottomStop, $topColor $topStop);

Is this a bug or a missing feature?

Regards,
Masi

**Comment by sds** [comment]
It is an issue in that you cannot exclude certain types (e.g. function names) from being linted by `NameFormat`. This relates to #389 so I'm going to close this as a duplicate.
