### ISSUE TITLE
Order of margin + padding should be TRBL

### ISSUE THREAD

**Issue by mrowles** [causes/scss-lint#394]
If you write a combined padding rule in CSS, such as `padding: 10px 15px 15px 10px`, the first rule is padding-top. Why does scsslint ask me to reorder `padding-left` before `padding-top`?

**Comment by lencioni** [comment]
Via https://github.com/causes/scss-lint/blob/master/lib/scss_lint/linter/README.md#propertysortorder:

> By default, will require properties be sorted in alphabetical order, as it's brain dead simple (highlight lines and execute :sort in vim), and it can benefit gzip compression.

You can also specify a custom order or use one of the preset orders found at https://github.com/causes/scss-lint/tree/master/data/property-sort-orders

I hope that helps!

**Comment by mrowles** [comment]
Great, thanks @lencioni :+1:
