### ISSUE TITLE
node-sass support

### ISSUE THREAD

**Issue by nottrobin** [causes/scss-lint#397]
Is anyone working on rebuilding this in Node for node-sass?

**Comment by sds** [comment]
Not that I know of, and it is not something that we have any interest in looking into or maintaining.

**Comment by lencioni** [comment]
I think these people might be working on it: https://github.com/Snugug/sass-lint

- https://github.com/Snugug/sass-lint/issues/2
- https://github.com/Snugug/sass-lint/issues/3

**Comment by nottrobin** [comment]
Thanks @lencioni that's really cool. I might get involved with that :)

**Comment by luqmaan** [comment]
FYI, sass-lint has moved to https://github.com/sasstools/sass-lint.
