### ISSUE TITLE
Linter not recognising spaces around colon in nested properties

### ISSUE THREAD

**Issue by gunnx** [causes/scss-lint#403]
If I have SCSS code like this:

```
.foo {
  font: {
    family :Arial,
    size :1em
  }
}
```

Rules **SpaceAfterPropertyColon** and **SpaceAfterPropertyName** do not fire for _family_ or _size_

Tested on Version: 0.34.0

**Comment by sds** [comment]
Thanks for the report, @gunnx!

Fixed in 9ee61dd46554e5b4d917c89f01412daf2df76744.
