### ISSUE TITLE
Add exceptions (#fff,#000) for ColorVariable

### ISSUE THREAD

**Issue by whmii** [causes/scss-lint#404]
I have seen this in quite a few projects but it often comes up that there is a need for pure white and pure black, outside the normal color plate of the project. Since they are used in arbitrary instances there is often no variable defined.

I would like to see the ability to define exceptions to the ColorVariable rule in the configuration. The ability to pass it particular hexes, that say 'don't worry about this one'.

the most typical use case is for a text or box shadow whose value is set with its opacity:

```
.foo {
  box-shadow: 0 1em 0.5em rgba(#000, 0.25);
}
```

I have seen *multiple* projects where designers, in an attempt to avoid this, have made variables like `$white` and `$black` which seems like a total smell.

https://github.com/causes/scss-lint/blob/master/lib/scss_lint/linter/README.md#colorvariable

**Comment by sds** [comment]
I agree that using the actual color name for the variable is a smell. It's not semantic (it doesn't tell you _what_ the color is for) and it's brittle in that if you decide to change from white/black you still have to update all the white/black references to their new color names.

Adding specific exceptions for black and white seems arbitrary to me.

Why not name the variables `$foreground` and `$background` (or whatever makes sense in your context)?

**Comment by chris-dura** [comment]
>Why not name the variables $foreground and $background (or whatever makes sense in your context)?

:+1:

**Comment by sds** [comment]
Closing due to lack of response.

**Comment by nene** [comment]
I add my vote for this feature request.

What if the site background isn't pure white and the text pure black, but I still want to use pure white and black in several unrelated places? It would then be totally wrong to use `$foreground` and `$background` as a substitute for pure black and white. In that case it seems better to just use `$black` and `$white`, which is silly as we could just have used `black` and `white` keywords.

The thing is, one can't just blindly substitute all uses of `black` and `white` with some variable, on needs to consider *why* something is black or white and define a variable accordingly. Like some black might be our default text color, while some other black might be our default border color. One will likely end up with multiple variables for black and white. This is all nice and tidy in ideal world, but such effort takes considerable time.

In reality I need to confront with code bases where colors `black` and `white` are my smallest concern. I'd rather concentrate my effort in eliminating all the cryptic hex codes scattered around the code base. I'd like the strictness of the linter to be more configurable. Currently scss-lint considers this code:

```css
a {
    color: blue;
    &:visited {
        color: purple;
    }
}
```

equally as bad as this code:

```
a {
    color: #3399ff;
    &:visited {
        color: #9966ff;
    }
}
```

which is IMHO totally unfair. I'm sure everybody would agree that the first snippet is way more readable then the latter.

**Comment by chris-dura** [comment]
More "readable", maybe... but the example below is arguably more "semantic". Attempting to enforce better semantics, which *should* translate to better code "understandability", is one major goal of `scss-lint`.

```scss
$link-color: #3399ff;
$link-color-visited: #9966ff;

...

a {
    color: $link-color;
    &:visited {
        color: $link-color-visited;
    }
}
```

**Comment by Skoks** [comment]
+1 for this feature :+1: 

* It’s quicker to type `#fff` and `#000` instead of $white and $black.
* There is never a time where you will update the variables $white or $black to be anything other then `#fff` or `#000`. If you do update these to be anything else, then you clearly are not writing semantic code.
